# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/mlite/mlite_pack.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/mlite/alu.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/mlite/bus_mux.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/cpu_pack.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/cache_cntrl.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/imports/mlite/cla.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/mlite/control.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/cpu_axi_rd_cntrl.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/cpu_axi_wr_cntrl.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/mem_cntrl.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/mlite/mem_ctrl.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/mlite/mlite_cpu.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/mlite/mult.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/mlite/pc_next.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/mlite/pipeline.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/mlite/reg_bank.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/mlite/shifter.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/cpu.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/crossbar_pack.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/crossbar.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/crossbar_axi_rd_cntrl.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/crossbar_axi_wr_cntrl.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/crossbar_base.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/crossbar_wrap_pack.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/crossbar_wrap.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/fpga/boot_pack_zynq.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/fpga/boot_pack_zynq_sim.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/fpga/main_pack_opcodes.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/bram.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/axi_full2lite_converter_pack.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/axi_full2lite_rd_cntrl.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/axi_full2lite_wr_cntrl.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/axi_full2lite_converter.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/uart_pack.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/uart_axi_rd_cntrl.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/uart_axi_wr_cntrl.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/uart_core.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/uart_fifo.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/rtl/platform/uart.vhd
  C:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/hdl/design_2_wrapper.vhd
}
add_files C:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/design_2.bd
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_5/bd_ebcc_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_6/bd_ebcc_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_7/bd_ebcc_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_8/bd_ebcc_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_9/bd_ebcc_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_10/bd_ebcc_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_11/bd_ebcc_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_xbar_0/design_2_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_xadc_wiz_0_0/design_2_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_xadc_wiz_0_0/design_2_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/sources_1/bd/design_2/design_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Projects/PDP_git/processor_design_project/fpga/zynq_fpga/zynq_fpga.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_2_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_2_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_2_wrapper_utilization_synth.rpt -pb design_2_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
