webtalk_init -webtalk_dir C:/Users/boblu/Documents/TuD/MSc_Computer_Engineering/PDP/pdp_test/pdp_test.sim/sim_1/behav/xsim/xsim.dir/cla_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 28 16:39:34 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dad34347-86b4-49ec-b9c3-3acccde1b932" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7c27cf2d131e48d19c8fabc21cb45c4a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5880_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1461664498 -regid "" -xml C:/Users/boblu/Documents/TuD/MSc_Computer_Engineering/PDP/pdp_test/pdp_test.sim/sim_1/behav/xsim/xsim.dir/cla_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/boblu/Documents/TuD/MSc_Computer_Engineering/PDP/pdp_test/pdp_test.sim/sim_1/behav/xsim/xsim.dir/cla_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/boblu/Documents/TuD/MSc_Computer_Engineering/PDP/pdp_test/pdp_test.sim/sim_1/behav/xsim/xsim.dir/cla_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
