@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun May 24 12:39:58 +0200 2020
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto efdb03bf26a7405495b13a895a2fa082 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_select_adder_behav xil_defaultlib.tb_select_adder -log elaborate.log"
call xelab  -wto efdb03bf26a7405495b13a895a2fa082 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_select_adder_behav xil_defaultlib.tb_select_adder -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
